apiVersion: v1
kind: Pod
metadata:
  name: ss
  namespace: default
spec:
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: ss1
    - image: redis
      imagePullPolicy: Always
      name: ss2
  nodeName: node1
  nodeSelector:
    kubernetes.io/hostname: node1
